import { useBreakpointValue, useToast, Box, BoxProps, Button, ButtonProps, Center, Flex, Text, Textarea } from '@chakra-ui/react';
import Head from 'next/head';
import Link from 'next/link';
import { useRef, useState, ChangeEventHandler } from 'react';

import { AppColors, HOVERABLE_CLASS } from '../constant';

// ********************************************************************************
// == Constant ====================================================================
const TOAST_DURATION = 2500/*T&E*/;

const buttonProps: Partial<ButtonProps> = {
  className: HOVERABLE_CLASS,
  color: AppColors.WHITE,
  backgroundColor: AppColors.PURPLE,
  _active: { color: AppColors.PURPLE, backgroundColor: AppColors.WHITE_2 },
  _hover: { color: AppColors.PURPLE, backgroundColor: AppColors.WHITE },
}

const containerProps: Partial<BoxProps> = {
  padding: '1em',
  flexBasis: '50%',
}

// == Component ===================================================================
const MainPage = () => {
  const outputDivRef = useRef<HTMLDivElement>(null/*default*/);
  const toast = useToast();

  // -- State ---------------------------------------------------------------------
  const [textAreaValue, setTextAreaValue] = useState('')

  // -- Handler -------------------------------------------------------------------
  const handleTextAreaChange: ChangeEventHandler<HTMLTextAreaElement> = (event) =>
    setTextAreaValue(event.target.value)

  const handleSetClipboard = (as: 'text' | 'html') => {
    const { current } = outputDivRef;
    if (!current) return/*not set yet*/;
    if (!textAreaValue) {
      toast({ description: 'No value to copy', status: 'error', duration: TOAST_DURATION });
      return/*no value*/;
    } /* else -- value exists */

    if (as === 'text') { navigator.clipboard.writeText(current.textContent ?? ''); }
    else { navigator.clipboard.write([new ClipboardItem({ 'text/html': new Blob([current.innerHTML], { type: 'text/html' }) })]); }

    toast({ description: `Copied as ${as === 'text' ? 'Text' : 'HTML'}`, status: 'success', duration: TOAST_DURATION })
  }

  // -- UI ------------------------------------------------------------------------
  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box
        position='relative'
        width='100vw'
        height='100vh'
        flexDir='column'
        justifyContent='space-between'
        overflowX='auto'
        overflowY='auto'
        color={AppColors.WHITE}
        backgroundColor={AppColors.BLACK_1}
      >
        <Box padding='2em'>
          <Text
            padding='0.25em'
            backgroundColor={AppColors.PURPLE}
            borderRadius='16px'
            width='fit-content'
            fontSize={useBreakpointValue({ base: '1.5em', md: '2.5em' })}
            fontWeight='bold'
          >
            Clipboard Injector
          </Text>
        </Box>
        <Box padding='2em'>
          <Flex
            backgroundColor={AppColors.BLACK_2}
            borderRadius='16px'
            flexDir={useBreakpointValue({ base: 'column', md: 'row' })}
            minHeight={useBreakpointValue({ base: '', md: '60vh' })}
          >
            <Box {...containerProps}>
              <Center padding='2em' gap='5em'>
                <Button {...buttonProps} onClick={() => handleSetClipboard('text')}>
                  {useBreakpointValue({ base: 'Text', md: 'Copy as Text' })}
                </Button>
                <Button {...buttonProps} onClick={() => handleSetClipboard('html')}>
                  {useBreakpointValue({ base: 'HTML', md: 'Copy as HTML' })}
                </Button>
              </Center>
              <Textarea
                value={textAreaValue}
                onChange={handleTextAreaChange}
                height='70%'/*T&E*/
              />
            </Box>
            <Box {...containerProps}>
              <Box
                padding='1em'
                height='100%'
                overflow='auto'
                outline={`1px solid ${AppColors.WHITE_2}`}
                borderRadius='16px'
              >
                <div ref={outputDivRef} style={{ all: 'revert'/*remove all styles*/ }} dangerouslySetInnerHTML={{ __html: textAreaValue.length ? textAreaValue : '<div>The rendered Text or HTML will appear here</div>' }} />
              </Box>
            </Box>
          </Flex>
        </Box>
        <Center>
          <Text>See the <Link href='https://github.com/Alan-Rodz/clipboard-injector' style={{ textDecoration: 'underline' }}>source code</Link> in GitHub</Text>
        </Center>
      </Box>
    </>
  )
}

export default MainPage;